first_project/first_app/urls.py
from django.urls import path
from first_app import views

urlpatterns = [
    path('index/', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('static-image/', views.img, name='img')
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from first_app import views
from django.conf.urls import include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('first_app/', include('first_app.urls')),
    path('second_app/', include('second_app.urls'))
]


first_project/second_app/urls.py
from django.urls import path
from second_app import views

app_name = 'second_app'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('users/', views.user, name='user'),
    path('form-details/', views.form_detail_view, name='form-details'),
    path('relative/', views.relative, name='relative')
]

first_project/first_app/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email_id = models.EmailField(max_length=80, unique=True)

    def __str__(self):
        return self.first_name

first_project/second_app/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email_id = models.EmailField(max_length=80, unique=True)

    def __str__(self):
        return self.first_name

class details(models.Model):
    add = models.CharField(max_length=200)

    def __str__(self):
        return self.add

first_project/second_app/forms.py
from django import forms
from django.forms.widgets import HiddenInput
from django.core import validators
from second_app.models import User

class FormDetails(forms.ModelForm):
    first_name = forms.CharField(widget=HiddenInput)
    class Meta:
        model = User
        fields = '__all__'

#class FormDetails(forms.Form):
   # first_name = forms.CharField()
    #last_name = forms.CharField()
    #email_id = forms.EmailField()
    #verify_email = forms.EmailField()
    #botcatcher = forms.CharField(required=False, widget=HiddenInput, validators=[validators.MaxLengthValidator(0)])

    #def clean_botcatcher(self):
       # botcatch = self.cleaned_data['botcatcher']
       # if len(botcatch)>0:
          #  raise forms.ValidationError("Bot Detected")
        #return botcatch

    #def clean_first_name(self):
        #first = self.cleaned_data['first_name']
        #if first[0].lower() !='z':
          #  raise forms.ValidationError("it should start with z")
       # return first

    #def clean(self):
       # get_all = super().clean()
        #if get_all['email_id'] != get_all['verify_email']:
          #  raise forms.ValidationError('Email does not match')

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.

def index(request):
    a = 5+5
    my_dict = {'insert_me': 'inserted from view', 'second_key': a}
    return render(request, 'first_app/index.html', my_dict)

def home(request):
    return HttpResponse("Welcome to Home")

def img(request):
    return render(request, 'first_app/static_image.html')


first_project/second_app/views.py
from django.shortcuts import render
from second_app.models import User
from second_app.forms import FormDetails

# Create your views here.
def index(request):
    return render(request, 'second_app/index.html')

def user(request):
    userlist = User.objects.order_by('first_name')
    mydict = {'user_list': userlist}
    return render(request, 'second_app/show_users.html', context=mydict)

def form_detail_view(request):
    form = FormDetails()
    if request.method == 'POST':
             print(form.is_valid())
             form = FormDetails(request.POST)
             if form.is_valid():
                 form.save()
                 #first = form.cleaned_data['first_name']
                 #last = form.cleaned_data['last_name']
                 #email = form.cleaned_data['email_id']

                 #User.objects.get_or_create(first_name=first, last_name=last, email_id=email)
                 #user = User(first_name=first, last_name=last, email_id=email)
                 #user.save()
    return render(request, 'second_app/form_details.html', {'form': form})

def relative(request):
    return render(request, 'second_app/relative_url.html')

first_project/templates/first_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome</title>
</head>
<body>
<h1>From Index.html</h1>
<h1>{{ insert_me }}</h1>
{{ second_key }}
</body>
</html>

first_project/templates/first_app/static_image.html
<!DOCTYPE html>
{%  load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}">
</head>
<body>
<h1>Welcome to Static Files</h1>
<img src = "{% static "images/maxresdefault.jpg" %}" alt="NOT FOUND">
</body>
</html>

first_project/templates/second_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>From Base HTML i.e base template</h1>
{% block body_block %}


{% endblock %}
</body>
</html>

first_project/templates/second_app/form_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
{{ form.as_p}}
    <input type="submit" value="submit">
    </form>
</body>
</html>

first_project/templates/second_app/index.html
<!DOCTYPE html>
{% extends 'second_app/base.html' %}
{% block body_block %}

<h1>Welcome to Index</h1>

{% endblock %}

first_project/templates/second_app/relative_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'second_app:user' %}">Show Users</a>
<a href="{% url 'second_app:index' %}">Back to Index</a>
<a href="{% url 'admin:index' %}">Admin</a>
</body>
</html>

first_project/templates/second_app/show_users.html
<!DOCTYPE html>
{% extends 'second_app/base.html' %}
{% block body_block %}


{% if user_list %}
    <table>
     <thead>
     <th>First Name</th>
     <th>Last Name</th>
     <th>Email</th>
     </thead>
    {% for user in user_list %}
    <tr>
        <td>{{ user.first_name }}</td>
        <td>{{ user.last_name }}</td>
        <td>{{ user.email_id }}</td>
    </tr>
    {% endfor %}
    </table>
    {% else %}
    <h1>Records not Found</h1>


{% endif %}
{% endblock %}